### ISSUE TITLE
Where does the output go to?

### ISSUE THREAD

**Issue by jurgenhaas** [tomas-zemres/fluent-plugin-fields-parser#3]
I'm testing with this plugin and wonder why I have to use `<match>` in the configuration and not `<filter>`. My understanding is that when a record once falls into a match that it is then consumed and will no longer be available for any subsequent match, but that's what I though this plugin was doing - preparing records for subsequent output.

A simple config looks like this:

```
<match app.matterbridge>
  type fields_parser
  parse_key log
</match>
<match app.matterbridge>
  type file
  path /tmp/matterbridge
</match>
```

There is no output what so ever. When I remove the fields_parser, then I'm getting the output in the /tmp directory. Probably just a simple mistake at my end, hoping that you can help me out.

**Comment by tomas-zemres** [comment]
Sorry, but I wrote this plugin 2 year ago and I do not use fluentd for long time. May be someone else helps you.

**Comment by jurgenhaas** [comment]
Well, then you should not that on the projects main page, if you no longer support that and also ask the guys from FluentD to remove it from the plugin list. Otherwise you're creating frustration with guys trying it finding out that it's getting them nowhere.

**Comment by wangzhuzhen** [comment]
@jurgenhaas 
I have the same issue. 
So, have you solved it now?

**Comment by yissachar** [comment]
FYI there is a [fork](https://github.com/matt-deboer/fluent-plugin-kvp-filter) that converts this to a filter plugin. Note that the readme there isn't properly updated, and you have to use `kvp` type, e.g.:

```
<filter pattern>
    @type       kvp
    parse_key   log_message
</filter>
```

**Comment by wangzhuzhen** [comment]
@yissachar  
nice!

**Comment by jurgenhaas** [comment]
I can confirm that the fork is working just fine.
