### ISSUE TITLE
1.4 compatible release

### ISSUE THREAD

**Issue by jpraet** [tomas-zemres/fluent-plugin-fields-parser#5]
Hi, I see the changes on the master branch have already been done to make the plugin compatible with fluentd 1.4.

Any timeframe on when this will get released?

Thanks

**Comment by tomas-zemres** [comment]
I changed version to 0.1.2 and tagged as v0.1.2

Is it OK?

**Comment by jpraet** [comment]
Could you publish it on https://rubygems.org/gems/fluent-plugin-fields-parser/?

**Comment by tomas-zemres** [comment]
Done
